# Generated by Django 6.0.1 on 2026-01-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpadeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(help_text='The 11-character YouTube Video ID', max_length=50)),
                ('session_type', models.CharField(choices=[('dig', 'The Dig (Interview)'), ('uncover', 'Uncover (Lyrics Breakdown)'), ('performance', 'Live Performance')], default='uncover', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoContent',
        ),
        migrations.AddField(
            model_name='song',
            name='is_spade_exclusive',
            field=models.BooleanField(default=False, help_text='Mark if this content is produced by Spade.'),
        ),
        migrations.AddField(
            model_name='spadesession',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spade_sessions', to='music.song'),
        ),
    ]
