# Generated by Django 5.2.10 on 2026-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_song_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="is_trending",
            field=models.BooleanField(
                default=False, help_text="Check this to show in the Trending section."
            ),
        ),
    ]
