# Generated by Django 6.0.1 on 2026-01-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_is_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(blank=True, help_text='Beats Per Minute', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='key',
            field=models.CharField(blank=True, help_text='e.g. C# Minor', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.producer'),
        ),
    ]
